---
output:
  github_document:
    html_preview: false
---

<!-- README.md and index.md are generated from README.Rmd. Please edit that file. -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/dropin-",
  out.width = "100%"
)

clean_output <- function(x, options) {
  x <- gsub("0x[0-9a-f]+", "0xdeadbeef", x)
  x <- gsub("dataframe_[0-9]*_[0-9]*", "      dataframe_42_42      ", x)
  x <- gsub("[0-9]*\\.___row_number ASC", "42.___row_number ASC", x)

  index <- x
  index <- gsub("─", "-", index)
  index <- strsplit(paste(index, collapse = "\n"), "\n---\n")[[1]][[2]]
  writeLines(index, "index.md")

  x <- fansi::strip_sgr(x)
  x
}

options(
  cli.num_colors = 256,
  cli.width = 71,
  width = 71,
  pillar.bold = TRUE,
  pillar.max_title_chars = 5,
  pillar.min_title_chars = 5,
  pillar.max_footer_lines = 12,
  conflicts.policy = list(warn = FALSE)
)

local({
  hook_source <- knitr::knit_hooks$get("document")
  knitr::knit_hooks$set(document = clean_output)
})

help <- function(...) {
  x <- utils::help(...)
  y <- utils:::.getHelpFile(x)
  z <- capture.output(tools::Rd2txt(y))
  out <- paste0("```\n", paste(gsub("_.", "", z), collapse = "\n"), "\n```")
  knitr::asis_output(out)
}
```

# dd

<!-- badges: start -->
<!-- badges: end -->

The goal of dd is to provide documentation for DuckDB's functions, and later also an easy way to test them.
It is meant to be used in conjunction with [duckplyr](https://duckplyr.tidyverse.org/) and [duckdb](https://duckdb.org/docs/stable/clients/r).


## Installation

You can install the development version of dd like so:

``` r
pak::pak("krlmlr/dd")
```

## Example

```{r example}
library(dd)
dd$acos

help(acos, package = "dd")
```
