utils::globalVariables("ANY")
utils::globalVariables("ANY[]")
utils::globalVariables("ANY[][]")
utils::globalVariables("BIGINT")
utils::globalVariables("BIGINT[]")
utils::globalVariables("BIT")
utils::globalVariables("BLOB")
utils::globalVariables("BOOLEAN[]")
utils::globalVariables("DOUBLE")
utils::globalVariables("INTEGER")
utils::globalVariables("INTERVAL")
utils::globalVariables("LAMBDA")
utils::globalVariables("MAP(ANY, ANY)")
utils::globalVariables("TIME WITH TIME ZONE")
utils::globalVariables("UNION")
utils::globalVariables("VARCHAR")
