utils::globalVariables("AGGREGATE_STATE<?>")
utils::globalVariables("ANY")
utils::globalVariables("ANY[]")
utils::globalVariables("BIGINT")
utils::globalVariables("BIGINT | DOUBLE | TIMESTAMP | ANY")
utils::globalVariables("BIGINT | HUGEINT")
utils::globalVariables("BIGINT | INTERVAL")
utils::globalVariables("BIGINT | TIMESTAMP | TIMESTAMP WITH TIME ZONE")
utils::globalVariables("BIGINT[]")
utils::globalVariables("BIGNUM | BIGINT | UBIGINT | HUGEINT | UHUGEINT")
utils::globalVariables("BIGNUM | UBIGINT | BIGINT | HUGEINT | UHUGEINT")
utils::globalVariables("BIT")
utils::globalVariables("BLOB")
utils::globalVariables("BOOLEAN")
utils::globalVariables("BOOLEAN[]")
utils::globalVariables("DATE | INTERVAL | TIME | TIMESTAMP | TIME WITH TIME ZONE | TIME_NS | TIMESTAMP WITH TIME ZONE")
utils::globalVariables("DATE | INTERVAL | TIMESTAMP | TIMESTAMP WITH TIME ZONE")
utils::globalVariables("DATE | INTERVAL | TIMESTAMP | TIMESTAMP WITH TIME ZONE | VARCHAR")
utils::globalVariables("DATE | TIME | TIMESTAMP | TIMESTAMP WITH TIME ZONE")
utils::globalVariables("DATE | TIMESTAMP | INTERVAL | TIME | TIME_NS | TIME WITH TIME ZONE | TIMESTAMP WITH TIME ZONE")
utils::globalVariables("DATE | TIMESTAMP | INTERVAL | TIME | TIME_NS | TIME WITH TIME ZONE | TIMESTAMP WITH TIME ZONE | BIGINT")
utils::globalVariables("DATE | TIMESTAMP | INTERVAL | TIME | TIME_NS | TIME WITH TIME ZONE | TIMESTAMP WITH TIME ZONE | TIMESTAMP_NS")
utils::globalVariables("DATE | TIMESTAMP | INTERVAL | TIME | TIME_NS | TIME WITH TIME ZONE | TIMESTAMP_NS | TIMESTAMP WITH TIME ZONE")
utils::globalVariables("DATE | TIMESTAMP | TIMESTAMP WITH TIME ZONE")
utils::globalVariables("DATE | TIMESTAMP | TIMESTAMP_NS | VARCHAR")
utils::globalVariables("DECIMAL | ANY")
utils::globalVariables("DECIMAL | BOOLEAN | SMALLINT | INTEGER | BIGINT | HUGEINT | DOUBLE | BIGNUM")
utils::globalVariables("DECIMAL | FLOAT | DOUBLE | DATE | TIMESTAMP | TIME | TIMESTAMP WITH TIME ZONE | TIME WITH TIME ZONE")
utils::globalVariables("DECIMAL | SMALLINT | INTEGER | BIGINT | HUGEINT | DOUBLE | DATE | TIME | TIME WITH TIME ZONE | TIMESTAMP | TIMESTAMP WITH TIME ZONE | TINYINT | FLOAT")
utils::globalVariables("DECIMAL | SMALLINT | INTEGER | BIGINT | HUGEINT | INTERVAL | DOUBLE | TIMESTAMP | TIMESTAMP WITH TIME ZONE | TIME | TIME WITH TIME ZONE")
utils::globalVariables("DECIMAL | TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | FLOAT | DOUBLE")
utils::globalVariables("DECIMAL | TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | FLOAT | DOUBLE | DATE | TIMESTAMP | TIME | TIMESTAMP WITH TIME ZONE | TIME WITH TIME ZONE")
utils::globalVariables("DOUBLE")
utils::globalVariables("DOUBLE | DOUBLE[]")
utils::globalVariables("DOUBLE | FLOAT")
utils::globalVariables("FLOAT | DOUBLE")
utils::globalVariables("FLOAT | DOUBLE | DATE | TIMESTAMP | TIMESTAMP WITH TIME ZONE")
utils::globalVariables("FLOAT | DOUBLE | DECIMAL")
utils::globalVariables("FLOAT | FLOAT[]")
utils::globalVariables("FLOAT[] | DOUBLE[]")
utils::globalVariables("FLOAT[3] | DOUBLE[3]")
utils::globalVariables("FLOAT[ANY] | DOUBLE[ANY]")
utils::globalVariables("INTEGER")
utils::globalVariables("INTEGER | BIGINT")
utils::globalVariables("INTEGER | BIGINT | DECIMAL")
utils::globalVariables("INTEGER | BIGINT | DOUBLE | VARCHAR | DATE | TIMESTAMP | TIMESTAMP WITH TIME ZONE | BLOB | DECIMAL | ANY")
utils::globalVariables("INTEGER | BIGINT | HUGEINT | DOUBLE | VARCHAR | DATE | TIMESTAMP | TIMESTAMP WITH TIME ZONE | BLOB | ANY")
utils::globalVariables("INTERVAL")
utils::globalVariables("K")
utils::globalVariables("K[]")
utils::globalVariables("LAMBDA")
utils::globalVariables("MAP(K, V)")
utils::globalVariables("STRUCT")
utils::globalVariables("STRUCT(\"year\" BIGINT, \"month\" BIGINT, \"day\" BIGINT)")
utils::globalVariables("STRUCT(K, V)[]")
utils::globalVariables("T")
utils::globalVariables("T | K | ANY")
utils::globalVariables("T[]")
utils::globalVariables("T[] | MAP(K, V) | STRUCT")
utils::globalVariables("T[] | VARCHAR")
utils::globalVariables("T[][]")
utils::globalVariables("TIME WITH TIME ZONE")
utils::globalVariables("TIME WITH TIME ZONE | TIMESTAMP | TIMESTAMP WITH TIME ZONE")
utils::globalVariables("TIMESTAMP | TIMESTAMP WITH TIME ZONE")
utils::globalVariables("TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | BIT")
utils::globalVariables("TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | FLOAT | DOUBLE | DECIMAL")
utils::globalVariables("TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | FLOAT | DOUBLE | DECIMAL | UTINYINT | USMALLINT | UINTEGER | UBIGINT | UHUGEINT")
utils::globalVariables("TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | FLOAT | DOUBLE | DECIMAL | UTINYINT | USMALLINT | UINTEGER | UBIGINT | UHUGEINT | BIGNUM | DATE | TIMESTAMP | INTERVAL")
utils::globalVariables("TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | FLOAT | DOUBLE | DECIMAL | UTINYINT | USMALLINT | UINTEGER | UBIGINT | UHUGEINT | BIGNUM | DATE | TIMESTAMP | INTERVAL | TIME | TIME WITH TIME ZONE")
utils::globalVariables("TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | FLOAT | DOUBLE | DECIMAL | UTINYINT | USMALLINT | UINTEGER | UBIGINT | UHUGEINT | DATE | INTERVAL | TIME | TIMESTAMP | TIME WITH TIME ZONE | BIGNUM")
utils::globalVariables("TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | FLOAT | DOUBLE | DECIMAL | UTINYINT | USMALLINT | UINTEGER | UBIGINT | UHUGEINT | INTERVAL")
utils::globalVariables("TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | FLOAT | DOUBLE | UTINYINT | USMALLINT | UINTEGER | UBIGINT | UHUGEINT")
utils::globalVariables("TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | UTINYINT | USMALLINT | UINTEGER | UBIGINT | UHUGEINT")
utils::globalVariables("TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | UTINYINT | USMALLINT | UINTEGER | UBIGINT | UHUGEINT | BIT")
utils::globalVariables("UNION")
utils::globalVariables("UUID")
utils::globalVariables("V[]")
utils::globalVariables("VARCHAR")
utils::globalVariables("VARCHAR | BIGINT")
utils::globalVariables("VARCHAR | BIT")
utils::globalVariables("VARCHAR | BOOLEAN")
utils::globalVariables("VARCHAR | DATE | TIMESTAMP | TIMESTAMP_NS")
utils::globalVariables("VARCHAR | UINTEGER")
utils::globalVariables("VARCHAR | VARCHAR[]")
utils::globalVariables("VARCHAR[]")
utils::globalVariables("VARCHAR[] | VARCHAR")
utils::globalVariables("VARIANT")
