# Generated by do_update_duckdb_funs(), do not edit by hand

`.dd.+` <- function(col0 = `TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | FLOAT | DOUBLE | DECIMAL | UTINYINT | USMALLINT | UINTEGER | UBIGINT | UHUGEINT | DATE | INTERVAL | TIME | TIMESTAMP | TIME WITH TIME ZONE | BIGNUM | TIMESTAMP WITH TIME ZONE | INET`, col1 = `TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | FLOAT | DOUBLE | DECIMAL | UTINYINT | USMALLINT | UINTEGER | UBIGINT | UHUGEINT | DATE | INTERVAL | TIME | TIMESTAMP | TIME WITH TIME ZONE | BIGNUM | TIMESTAMP WITH TIME ZONE`) {
  stop("DuckDB function +() is not available in R.")
}

.dd.format <- function(format = VARCHAR) {
  stop("DuckDB function format() is not available in R.")
}

.dd.length <- function(string = VARCHAR) {
  stop("DuckDB function length() is not available in R.")
}

`.dd.-` <- function(col0 = `TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | FLOAT | DOUBLE | DECIMAL | UTINYINT | USMALLINT | UINTEGER | UBIGINT | UHUGEINT | BIGNUM | DATE | TIMESTAMP | INTERVAL | TIME | TIME WITH TIME ZONE | TIMESTAMP WITH TIME ZONE | INET`, col1 = `TINYINT | SMALLINT | INTEGER | BIGINT | HUGEINT | FLOAT | DOUBLE | DECIMAL | UTINYINT | USMALLINT | UINTEGER | UBIGINT | UHUGEINT | BIGNUM | DATE | TIMESTAMP | INTERVAL | TIMESTAMP WITH TIME ZONE`) {
  stop("DuckDB function -() is not available in R.")
}

